project_id = "dqtjhkncshsnoxjcwtjw"

[functions.generate-campaign]
verify_jwt = false

[functions.score-campaign]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false
